# Generated by Django 5.0.2 on 2025-02-10 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StoreConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enable_online_payment', models.BooleanField(default=False)),
                ('payment_gateway', models.CharField(choices=[('STRIPE', 'Stripe'), ('PAYPAL', 'PayPal'), ('CASH', 'Cash Only')], default='CASH', max_length=20)),
                ('stripe_public_key', models.CharField(blank=True, max_length=255)),
                ('stripe_secret_key', models.CharField(blank=True, max_length=255)),
                ('paypal_client_id', models.CharField(blank=True, max_length=255)),
                ('paypal_secret', models.CharField(blank=True, max_length=255)),
                ('enable_order_emails', models.BooleanField(default=False)),
                ('smtp_host', models.CharField(blank=True, max_length=255)),
                ('smtp_port', models.IntegerField(blank=True, null=True)),
                ('smtp_username', models.CharField(blank=True, max_length=255)),
                ('smtp_password', models.CharField(blank=True, max_length=255)),
                ('from_email', models.EmailField(blank=True, max_length=254)),
                ('admin_email', models.EmailField(blank=True, max_length=254)),
            ],
            options={
                'verbose_name': 'Store Configuration',
                'verbose_name_plural': 'Store Configuration',
            },
        ),
    ]
