# Generated by Django 5.0.2 on 2025-02-10 04:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_storeconfiguration'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentAnalytics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True)),
                ('total_transactions', models.IntegerField(default=0)),
                ('successful_transactions', models.IntegerField(default=0)),
                ('failed_transactions', models.IntegerField(default=0)),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('refund_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
            ],
            options={
                'verbose_name_plural': 'Payment Analytics',
            },
        ),
        migrations.RenameField(
            model_name='storeconfiguration',
            old_name='paypal_client_id',
            new_name='cbq_merchant_id',
        ),
        migrations.RenameField(
            model_name='storeconfiguration',
            old_name='paypal_secret',
            new_name='cbq_secret_key',
        ),
        migrations.RenameField(
            model_name='storeconfiguration',
            old_name='stripe_public_key',
            new_name='cbq_terminal_id',
        ),
        migrations.RenameField(
            model_name='storeconfiguration',
            old_name='stripe_secret_key',
            new_name='fatoora_api_key',
        ),
        migrations.AddField(
            model_name='storeconfiguration',
            name='enable_sms_notifications',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='storeconfiguration',
            name='fatoora_merchant_id',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='storeconfiguration',
            name='naps_merchant_id',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='storeconfiguration',
            name='naps_secret_key',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='storeconfiguration',
            name='ooredoo_api_key',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='storeconfiguration',
            name='ooredoo_merchant_id',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='storeconfiguration',
            name='qnb_merchant_id',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='storeconfiguration',
            name='qnb_secret_key',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='storeconfiguration',
            name='qpay_api_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='storeconfiguration',
            name='qpay_merchant_id',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='storeconfiguration',
            name='qpay_secret_key',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='storeconfiguration',
            name='sms_api_key',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='storeconfiguration',
            name='sms_provider',
            field=models.CharField(blank=True, choices=[('OOREDOO', 'Ooredoo'), ('VODAFONE', 'Vodafone')], max_length=20),
        ),
        migrations.AddField(
            model_name='storeconfiguration',
            name='tap_public_key',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='storeconfiguration',
            name='tap_secret_key',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='storeconfiguration',
            name='payment_gateway',
            field=models.CharField(choices=[('CASH', 'Cash Only'), ('QPAY', 'QPay'), ('CBQ', 'CBQ Payment Gateway'), ('NAPS', 'NAPS Gateway'), ('QNB', 'QNB Pay'), ('TAP', 'Tap Payments'), ('FATOORA', 'Fatoora'), ('OOREDOO', 'Ooredoo Money')], default='CASH', max_length=20),
        ),
        migrations.CreateModel(
            name='PaymentLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_id', models.CharField(max_length=255)),
                ('gateway', models.CharField(choices=[('CASH', 'Cash Only'), ('QPAY', 'QPay'), ('CBQ', 'CBQ Payment Gateway'), ('NAPS', 'NAPS Gateway'), ('QNB', 'QNB Pay'), ('TAP', 'Tap Payments'), ('FATOORA', 'Fatoora'), ('OOREDOO', 'Ooredoo Money')], max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(choices=[('INITIATED', 'Payment Initiated'), ('PROCESSING', 'Processing'), ('SUCCESS', 'Success'), ('FAILED', 'Failed'), ('CANCELLED', 'Cancelled'), ('REFUNDED', 'Refunded')], max_length=20)),
                ('response_data', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_logs', to='orders.order')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Refund',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('reason', models.TextField()),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('PROCESSED', 'Processed'), ('REJECTED', 'Rejected')], default='PENDING', max_length=20)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='refunds', to='orders.order')),
                ('processed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
